from abc import abstractmethod
from typing import Literal, overload

from numpy import float64
from numpy.typing import NDArray

from .. import Point3D, Vector3D

class _TargetedSampler:
    _total_weight: float
    _targets: tuple[tuple[Point3D, float, float], ...]
    _cdf: NDArray[float64]

    def __init__(self, targets: list[tuple[Point3D, float, float]]) -> None:
        """
        Targets is a list of tuples describing the target spheres and their weighting.

        Each target tuple consists of (Point3D sphere_centre, double sphere_radius, double weight).

        :param list targets: A list of tuples describing spheres for targeted sampling.
        """

    @overload
    def __call__(self, point: Point3D, samples: None = None, pdf: Literal[False] = False) -> Vector3D: ...
    @overload
    def __call__(self, point: Point3D, samples: int, pdf: Literal[False] = False) -> list[Vector3D]: ...
    @overload
    def __call__(self, point: Point3D, samples: None = None, pdf: Literal[True] = True) -> tuple[Vector3D, float]: ...
    @overload
    def __call__(self, point: Point3D, samples: int, pdf: Literal[True] = True) -> list[tuple[Vector3D, float]]: ...
    def __call__(self, point: Point3D, samples: int | None = None, pdf: bool = False) -> Vector3D | tuple[Vector3D, float] | list[Vector3D] | list[tuple[Vector3D, float]]:
        """
        If samples is not provided, returns a single Vector3D sample from
        the distribution. If samples is set to a value then a number of
        samples equal to the value specified is returned in a list.

        If pdf is set to True the Vector3D sample is returned inside a tuple
        with its associated pdf value as the second element.

        :param int samples: Number of points to generate (default=None).
        :param bool pdf: Toggle for returning associated sample pdfs (default=False).
        :return: A Vector3D, tuple or list of Vector3D objects.
        """
    @abstractmethod
    def pdf(self, point: Point3D, sample: Vector3D) -> float:
        """
        Calculates the value of the PDF for the specified sample point and direction.

        :param Point3D point: The point from which to sample.
        :param Vector3D sample: The sample direction.
        :rtype: double
        """

class TargetedHemisphereSampler(_TargetedSampler):
    """
    Generates vectors on a hemisphere targeting a set of target spheres.

    This sampler takes a list of spheres and corresponding weighting factors.
    To generate a sample a sphere is randomly selected according the
    distribution of the sphere weights and launches a ray at the solid angle
    subtended by the target sphere.

    If the targeted sphere intersects with the hemisphere's base plane, lies
    behind the plane, or the origin point from which samples are generated lies
    inside the target sphere, a sample is randomly selected from the full hemisphere
    using a cosine weighted distribution.

    The hemisphere is aligned so the hemisphere base lies on the x-y plane and
    the points along the +ve z axis.
    """

    def pdf(self, point: Point3D, sample: Vector3D) -> float:
        """
        Calculates the value of the PDF for the specified sample point and direction.

        :param Point3D point: The point from which to sample.
        :param Vector3D sample: The sample direction.
        :rtype: double
        """

class TargetedSphereSampler(_TargetedSampler):
    """
    Generates vectors targeting a set of target spheres.

    This sampler takes a list of spheres and corresponding weighting factors.
    To generate a sample a sphere is randomly selected according the
    distribution of the sphere weights and launches a ray at the solid angle
    subtended by the target sphere.

    If the origin point, from which samples are generated, lies inside the
    target sphere. A random sample is generated by uniformly sampling over the
    full sphere.
    """

    def pdf(self, point: Point3D, sample: Vector3D) -> float:
        """
        Calculates the value of the PDF for the specified sample point and direction.

        :param Point3D point: The point from which to sample.
        :param Vector3D sample: The sample direction.
        :rtype: double
        """
