from .processor import PixelProcessor
from .slice import SpectralSlice

class Pipeline0D:
    """
    The base class for 0D pipelines.
    """

    def initialise(
        self,
        min_wavelength: float,
        max_wavelength: float,
        spectral_bins: int,
        spectral_slices: list[SpectralSlice],
        quiet: bool,
    ) -> None:
        """
        Initialises containers for the pipeline's processing output.

        The deriving class should use this method to perform any initialisation needed
        for their calculations.

        This is a virtual method and must be implemented in a sub class.

        :param float min_wavelength: The minimum wavelength in the spectral range.
        :param float max_wavelength: The maximum wavelength in the spectral range.
        :param int spectral_bins: Number of spectral samples across wavelength range.
        :param list spectral_slices: List of spectral sub-ranges for cases where spectral
          rays is > 1 (i.e. dispersion effects turned on).
        :param bool quiet: When True, suppresses output to the terminal.
        """
    def pixel_processor(self, slice_id: int) -> PixelProcessor:
        """
        Initialise and return a pixel processor for this pipeline.

        Called by worker threads, each worker will request a pixel processor for
        processing the output of their work from each pipeline.

        This is a virtual method and must be implemented in a sub class.

        :param int slice_id: The integer identifying the spectral slice being worked on
          by the requesting worker thread.
        :rtype: PixelProcessor
        """
    def update(self, slice_id: int, packed_result: tuple, samples: int) -> None:
        """
        Updates the internal results array with packed results from the pixel processor.

        After worker threads have observed the world and used the pixel processor to
        process the spectra into packed results, the worker then passes the packed results
        to the pipeline with the update() method.

        If this pipeline implements some form of visualisation, update the visualisation
        at the end of this method.

        This is a virtual method and must be implemented in a sub class.

        :param int slice_id: The integer identifying the spectral slice being worked on
          by the worker thread.
        :param tuple packed_result: The tuple of results generated by this pipeline's
          PixelProcessor.
        :param int samples: The number of samples taken by the worker. Needed for ensuring
          accuracy of statistical errors when combining new samples with previous results.
        """
    def finalise(self) -> None:
        """
        Finalises the results when rendering has finished.

        This method is called when all workers have finished sampling and the results need
        to undergo any final processing.

        If this pipeline implements some form of visualisation, use this method to plot the
        final visualisation of results.

        This is a virtual method and must be implemented in a sub class.
        """

class Pipeline1D:
    """
    The base class for 1D pipelines.
    """

    def initialise(
        self,
        pixels: int,
        pixel_samples: int,
        min_wavelength: float,
        max_wavelength: float,
        spectral_bins: int,
        spectral_slices: list[SpectralSlice],
        quiet: bool,
    ) -> None:
        """
        Initialises containers for the pipeline's processing output.

        The deriving class should use this method to perform any initialisation needed
        for their calculations.

        This is a virtual method and must be implemented in a sub class.

        :param tuple pixels: A tuple defining the pixel dimensions being sampled
          (i.e. (256,)).
        :param int pixel_samples: The number of samples being taken per pixel. Needed
          for statistical calculations.
        :param float min_wavelength: The minimum wavelength in the spectral range.
        :param float max_wavelength: The maximum wavelength in the spectral range.
        :param int spectral_bins: Number of spectral samples across wavelength range.
        :param list spectral_slices: List of spectral sub-ranges for cases where spectral
          rays is > 1 (i.e. dispersion effects turned on).
        :param bool quiet: When True, suppresses output to the terminal.
        """
    def pixel_processor(self, pixel: int, slice_id: int) -> PixelProcessor:
        """
        Initialise and return a pixel processor for this pipeline and pixel coordinate.

        Called by worker threads, each worker will request a pixel processor for
        the pixel they are processing.

        This is a virtual method and must be implemented in a sub class.

        :param int pixel: The pixel coordinate of the pixel being sampled by the worker.
        :param int slice_id: The integer identifying the spectral slice being worked on
          by the requesting worker thread.
        :rtype: PixelProcessor
        """
    def update(self, pixel: int, slice_id: int, packed_result: tuple) -> None:
        """
        Updates the internal results array with packed results from the pixel processor.

        After worker threads have observed the world and used the pixel processor to
        process the spectra into packed results, the worker then passes the packed results
        for the current pixel to the pipeline with the update() method. This method should
        add the results for this pixel to the pipeline's results array.

        If this pipeline implements some form of visualisation, update the visualisation
        at the end of this method.

        This is a virtual method and must be implemented in a sub class.

        :param int pixel: The integer identifying the pixel being worked on.
        :param int slice_id: The integer identifying the spectral slice being worked on
          by the worker thread.
        :param tuple packed_result: The tuple of results generated by this pipeline's
          PixelProcessor.
        """
    def finalise(self) -> None:
        """
        Finalises the results when rendering has finished.

        This method is called when all workers have finished sampling and the results need
        to undergo any final processing.

        If this pipeline implements some form of visualisation, use this method to plot the
        final visualisation of results.

        This is a virtual method and must be implemented in a sub class.
        """

class Pipeline2D:
    """
    The base class for 2D pipelines.
    """

    def initialise(
        self,
        pixels: tuple[int, int],
        pixel_samples: int,
        min_wavelength: float,
        max_wavelength: float,
        spectral_bins: int,
        spectral_slices: list[SpectralSlice],
        quiet: bool,
    ) -> None:
        """
        Initialises containers for the pipeline's processing output.

        The deriving class should use this method to perform any initialisation needed
        for their calculations.

        This is a virtual method and must be implemented in a sub class.

        :param tuple pixels: A tuple defining the pixel dimensions being sampled
          (i.e. (512, 512)).
        :param int pixel_samples: The number of samples being taken per pixel. Needed
          for statistical calculations.
        :param float min_wavelength: The minimum wavelength in the spectral range.
        :param float max_wavelength: The maximum wavelength in the spectral range.
        :param int spectral_bins: Number of spectral samples across wavelength range.
        :param list spectral_slices: List of spectral sub-ranges for cases where spectral
          rays is > 1 (i.e. dispersion effects turned on).
        :param bool quiet: When True, suppresses output to the terminal.
        """
    def pixel_processor(self, x: int, y: int, slice_id: int) -> PixelProcessor:
        """
        Initialise and return a pixel processor for this pipeline and pixel coordinate.

        Called by worker threads, each worker will request a pixel processor for
        the pixel they are currently processing.

        This is a virtual method and must be implemented in a sub class.

        :param int x: The x pixel coordinate (x, y) of the pixel being sampled by the worker.
        :param int y: The y pixel coordinate (x, y) of the pixel being sampled by the worker.
        :param int slice_id: The integer identifying the spectral slice being worked on
          by the requesting worker thread.
        :rtype: PixelProcessor
        """
    def update(self, x: int, y: int, slice_id: int, packed_result: tuple) -> None:
        """
        Updates the internal results array with packed results from the pixel processor.

        After worker threads have observed the world and used the pixel processor to
        process the spectra into packed results, the worker then passes the packed results
        for the current pixel to the pipeline with the update() method. This method should
        add the results for this pixel to the pipeline's results array.

        If this pipeline implements some form of visualisation, update the visualisation
        at the end of this method.

        This is a virtual method and must be implemented in a sub class.

        :param int x: The x pixel coordinate (x, y) of the pixel being sampled by the worker.
        :param int y: The y pixel coordinate (x, y) of the pixel being sampled by the worker.
        :param int slice_id: The integer identifying the spectral slice being worked on
          by the worker thread.
        :param tuple packed_result: The tuple of results generated by this pipeline's
          PixelProcessor.
        """
    def finalise(self) -> None:
        """
        Finalises the results when rendering has finished.

        This method is called when all workers have finished sampling and the results need
        to undergo any final processing.

        If this pipeline implements some form of visualisation, use this method to plot the
        final visualisation of results.

        This is a virtual method and must be implemented in a sub class.
        """
