from typing import Any, Literal

from .mesh import Mesh

PLY_AUTOMATIC: Literal["auto"] = "auto"
PLY_ASCII: Literal["ascii"] = "ascii"
PLY_BINARY: Literal["binary"] = "binary"

class PLYHandler:
    @classmethod
    def import_ply(
        cls,
        filename: str,
        scaling: float = 1.0,
        mode: Literal["auto", "ascii", "binary"] = PLY_AUTOMATIC,
        **kwargs: Any,
    ) -> Mesh:
        """
        Create a mesh instance from a Polygon File Format (PLY) mesh file (.ply).
        Note PLY is also known as the Stanford Triangle Format.

        Some engineering meshes are exported in different units (mm for example)
        whereas Raysect units are in m. Applying a scale factor of 0.001 would
        convert the mesh into m for use in Raysect.

        :param str filename: Mesh file path.
        :param double scaling: Scale the mesh by this factor (default=1.0).
        :param str mode: The file format to load: 'ascii', 'binary', 'auto' (default='auto').
        :param kwargs: Accepts optional keyword arguments from the Mesh class.
        :rtype: Mesh

        .. code-block:: pycon

            >>> from raysect.optical import World, translate, rotate, ConstantSF, Sellmeier, Dielectric
            >>> from raysect.primitive import import_ply
            >>>
            >>> world = World()
            >>>
            >>> diamond = Dielectric(Sellmeier(0.3306, 4.3356, 0.0, 0.1750**2, 0.1060**2, 0.0),
            >>>                      ConstantSF(1.0))
            >>>
            >>> mesh = import_ply("your_mesh.ply", scaling=1, mode='binary', parent=world,
            >>>                   transform=translate(0, 0, 0)*rotate(165, 0, 0), material=diamond)
        """
    @classmethod
    def export_ply(
        cls,
        mesh: Mesh,
        filename: str,
        mode: Literal["ascii", "binary"] = PLY_BINARY,
        comment: str = "Generated by Raysect",
    ) -> None:
        """
        Write a mesh instance to a Polygon File Format (PLY) mesh file (.ply).
        Note PLY is also known as the Stanford Triangle Format.

        :param Mesh mesh: The Raysect mesh instance to write as PLY.
        :param str filename: Mesh file path.
        :param str mode: The file format to write: 'ascii', 'binary' (default='binary').
        :param str comment: An optional string comment to include in the output file,
          can be multiple lines.

        .. code-block:: pycon

            >>> mesh
            <raysect.primitive.mesh.mesh.Mesh at 0x7f2c09eac2e8>
            >>> from raysect.primitive import export_ply
            >>> export_ply(mesh, 'my_mesh.ply', mode='ascii', comment='My mesh')
        """

def import_ply(
    filename: str,
    scaling: float = 1.0,
    mode: Literal["auto", "ascii", "binary"] = PLY_AUTOMATIC,
    **kwargs: Any,
) -> Mesh:
    """
    Create a mesh instance from a Polygon File Format (PLY) mesh file (.ply).
    Note PLY is also known as the Stanford Triangle Format.

    Some engineering meshes are exported in different units (mm for example)
    whereas Raysect units are in m. Applying a scale factor of 0.001 would
    convert the mesh into m for use in Raysect.

    :param str filename: Mesh file path.
    :param double scaling: Scale the mesh by this factor (default=1.0).
    :param str mode: The file format to load: 'ascii', 'binary', 'auto' (default='auto').
    :param kwargs: Accepts optional keyword arguments from the Mesh class.
    :rtype: Mesh

    .. code-block:: pycon

        >>> from raysect.optical import World, translate, rotate, ConstantSF, Sellmeier, Dielectric
        >>> from raysect.primitive import import_ply
        >>>
        >>> world = World()
        >>>
        >>> diamond = Dielectric(Sellmeier(0.3306, 4.3356, 0.0, 0.1750**2, 0.1060**2, 0.0),
        >>>                      ConstantSF(1.0))
        >>>
        >>> mesh = import_ply("your_mesh.ply", scaling=1, mode='binary', parent=world,
        >>>                   transform=translate(0, 0, 0)*rotate(165, 0, 0), material=diamond)
    """

def export_ply(
    mesh: Mesh,
    filename: str,
    mode: Literal["ascii", "binary"] = PLY_BINARY,
    comment: str = "Generated by Raysect",
) -> None:
    """
    Write a mesh instance to a Polygon File Format (PLY) mesh file (.ply).
    Note PLY is also known as the Stanford Triangle Format.

    :param Mesh mesh: The Raysect mesh instance to write as PLY.
    :param str filename: Mesh file path.
    :param str mode: The file format to write: 'ascii', 'binary' (default='binary').
    :param str comment: An optional string comment to include in the output file,
      can be multiple lines.

    .. code-block:: pycon

        >>> mesh
        <raysect.primitive.mesh.mesh.Mesh at 0x7f2c09eac2e8>
        >>> from raysect.primitive import export_ply
        >>> export_ply(mesh, 'my_mesh.ply', mode='ascii', comment='My mesh')
    """
