"""Math module type stubs."""

from typing import Any, TypeAlias

Number: TypeAlias = int | float
Vector3: TypeAlias = tuple[float, float, float]

class Point3D:
    x: float
    y: float
    z: float

    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def __add__(self, other: Vector3D) -> Point3D: ...
    def __sub__(self, other: Point3D) -> Vector3D: ...

class Vector3D:
    x: float
    y: float
    z: float

    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def __add__(self, other: Vector3D) -> Vector3D: ...
    def __sub__(self, other: Vector3D) -> Vector3D: ...
    def __mul__(self, scalar: Number) -> Vector3D: ...
    def __truediv__(self, scalar: Number) -> Vector3D: ...
    def dot(self, other: Vector3D) -> float: ...
    def cross(self, other: Vector3D) -> Vector3D: ...
    def normalise(self) -> Vector3D: ...
    def get_length(self) -> float: ...

class Normal3D:
    x: float
    y: float
    z: float

    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...

class AffineMatrix3D:
    def __init__(self, *args: Any) -> None: ...
    def __mul__(
        self, other: AffineMatrix3D | Vector3D | Point3D
    ) -> AffineMatrix3D | Vector3D | Point3D: ...
    def inverse(self) -> AffineMatrix3D: ...
    def transpose(self) -> AffineMatrix3D: ...

def rotate_x(angle: float) -> AffineMatrix3D: ...
def rotate_y(angle: float) -> AffineMatrix3D: ...
def rotate_z(angle: float) -> AffineMatrix3D: ...
def translate(x: float, y: float, z: float) -> AffineMatrix3D: ...
def scale(x: float, y: float = ..., z: float = ...) -> AffineMatrix3D: ...
