"""Type stubs for raysect.core.math._vec3"""

from typing import Iterator

# No public API detected - may need manual inspection
class _Vec3:
    """Base class for 3D vector types."""

    x: float
    y: float
    z: float

    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getstate__(self) -> tuple[float, float, float]: ...
    def __setstate__(self, state: object) -> None: ...

    @property
    def length(self) -> float: ...

    def dot(self, v: _Vec3) -> float: ...
    def angle(self, v: _Vec3) -> float: ...
