from ._vec3 import _Vec3  # pyright: ignore[reportPrivateUsage]
from .affinematrix import AffineMatrix3D
from .vector import Vector3D

class Normal3D(_Vec3):
    """
    Represents a normal vector in 3D affine space.

    A Normal3D is just a special case of a Vector3D that is perpendicular to a surface. A normal can be generated by
    taking the cross product of two non parallel Vectors that lie inside the surface. Because a Normal3D is defined
    in terms of a surface it supports a reduced set of operations when compared with Vectors.

    If no initial values are passed, Normal3D defaults to a unit vector
    aligned with the z-axis: Normal3D(0.0, 0.0, 1.0)

    :param float x: initial x coordinate, defaults to x = 0.0.
    :param float y: initial y coordinate, defaults to y = 0.0.
    :param float z: initial z coordinate, defaults to z = 0.0.

    :ivar float x: x-coordinate
    :ivar float y: y-coordinate
    :ivar float z: z-coordinate

    .. code-block:: pycon

        >>> from raysect.core import Normal3D
        >>> a = Normal3D(0, 0, 1)
    """

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 1.0) -> None: ...
    def __repr__(self) -> str:
        """Returns a string representation of the Normal3D object."""
    def __richcmp__(self, other: Normal3D, op: int) -> bool:
        """Provides basic normal comparison operations."""
    def __neg__(self) -> Normal3D:
        """Returns a normal with the reverse orientation."""
    def __add__(self, y: _Vec3) -> Normal3D:
        """Addition operator."""
    def __radd__(self, x: _Vec3) -> Normal3D:
        """Reverse addition operator."""
    def __sub__(self, y: _Vec3) -> Normal3D:
        """Subtract operator."""
    def __rsub__(self, x: _Vec3) -> Normal3D:
        """Reverse subtract operator."""
    def __mul__(self, y: float) -> Normal3D:
        """Multiply operator."""
    def __rmul__(self, x: float | AffineMatrix3D) -> Normal3D:
        """Reverse multiply operator."""
    def __truediv__(self, y: float) -> Normal3D:
        """Division operator."""
    def cross(self, v: _Vec3) -> Vector3D:
        """
        Calculates the cross product between this vector and the supplied vector

        C = A.cross(B) <=> C = A x B

        :param Vector3D v: An input vector with which to calculate the cross product.
        :rtype: Vector3D
        """
    def normalise(self) -> Normal3D:
        """
        Returns a normalised copy of the normal vector.

        The returned normal is normalised to length 1.0 - a unit vector.

        :rtype: Normal3D
        """
    def transform(self, m: AffineMatrix3D) -> Normal3D:
        """
        Transforms the normal with the supplied Affine Matrix.

        The normal is multiplied by the inverse transpose of the transform
        matrix. This resulting normal remains perpendicular to its surface post
        transform.

        Warning: this method performs a costly inversion of the supplied matrix.
        If an inverse matrix is already available in scope, use the
        transform_with_inverse() method as it is considerably faster.

        For cython code this method is substantially faster than using the
        multiplication operator of the affine matrix.

        :param AffineMatrix3D m: The affine matrix describing the required coordinate transformation.
        :return: A new instance of this normal vector that has been transformed with the supplied Affine Matrix.
        :rtype: Normal3D
        """
    def transform_with_inverse(self, m: AffineMatrix3D) -> Normal3D:
        """
        Transforms the normal with the supplied inverse Affine Matrix.

        If an inverse matrix is already available in scope, this method is
        considerably faster than the transform() method - it skips a matrix
        inversion required to calculate the transformed normal (see the
        transform() documentation).

        For cython code this method is substantially faster than using the
        multiplication operator of the affine matrix.

        :param AffineMatrix3D m: An inverse affine matrix of the required coordinate transformation.
        :return: A new instance of this normal vector that has been transformed.
        :rtype: Normal3D
        """
    def copy(self) -> Normal3D:
        """
        Returns a copy of the normal.

        :rtype: Normal3D
        """
    def as_vector(self) -> Vector3D:
        """
        Returns a Vector3D copy of the normal.

        :rtype: Vector3D
        """
    def orthogonal(self) -> Vector3D:
        """
        Returns a unit vector that is guaranteed to be orthogonal to the normal.

        :rtype: Vector3D
        """
