"""Type stubs for raysect.core.math.point"""

from collections.abc import Iterator

from raysect.core.math.affinematrix import AffineMatrix3D
from raysect.core.math.vector import Vector2D, Vector3D

class Point2D:
    """Represents a point in 2D affine space."""

    x: float
    y: float

    def __init__(self, x: float = ..., y: float = ...) -> None: ...
    def __repr__(self) -> str: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def __add__(self, y: object) -> Vector2D: ...
    def __sub__(self, y: object) -> Vector2D: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getstate__(self) -> tuple[float, float]: ...
    def __setstate__(self, state: object) -> None: ...
    def copy(self) -> Point2D: ...
    def distance_to(self, p: Point2D) -> float: ...
    def vector_to(self, p: Point2D) -> Vector2D: ...

class Point3D:
    """Represents a point in 3D affine space."""

    x: float
    y: float
    z: float

    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def __repr__(self) -> str: ...
    def __richcmp__(self, other: object, op: int) -> bool: ...
    def __add__(self, other: object) -> Vector3D: ...
    def __sub__(self, other: object) -> Vector3D: ...
    def __rmul__(self, x: object) -> Point3D: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getstate__(self) -> tuple[float, float, float]: ...
    def __setstate__(self, state: object) -> None: ...
    def copy(self) -> Point3D: ...
    def distance_to(self, p: Point3D) -> float: ...
    def transform(self, m: AffineMatrix3D) -> Point3D: ...
    def vector_to(self, p: Point3D) -> Vector3D: ...
