from ..intersection import Intersection
from ..math import Point3D
from ..ray import Ray
from ..scenegraph.primitive import Primitive

class Accelerator:
    def build(self, primitives: list[Primitive]) -> None: ...
    def hit(self, ray: Ray) -> Intersection | None: ...
    def contains(self, point: Point3D) -> list[Primitive]: ...
