from ..intersection import Intersection
from ..math import Point3D
from ..ray import Ray
from ..scenegraph.primitive import Primitive
from .accelerator import Accelerator

class Unaccelerated(Accelerator):
    def __init__(self) -> None: ...
    def build(self, primitives: list[Primitive]) -> None: ...
    def hit(self, ray: Ray) -> Intersection | None: ...
    def contains(self, point: Point3D) -> list[Primitive]: ...
